### ISSUE TITLE
Register on https://joss.theoj.org/ and Write the orcid

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/How-Open-is-Open-Source#1]
Guys, please create an account on https://joss.theoj.org/ and write your `orcid` as a comment on this ticket. After you register you will receive the `orcid` checkout the email id you created the account w/.

**Comment by shah-aman** [comment]
https://orcid.org/0000-0002-9739-360X

**Comment by bymayanksingh** [comment]
https://orcid.org/0000-0003-4108-424X

**Comment by ucalyptus** [comment]
https://orcid.org/0000-0002-3377-0293
